from __future__ import annotations

from source_items import Item


def item(
    question: str,
    correct: str,
    wrong: str,
    distractor_1: str,
    distractor_2: str,
    note: str,
) -> Item:
    return Item(
        question,
        correct,
        wrong,
        distractor_1,
        distractor_2,
        note,
    )


def build_easy_items() -> list[Item]:
    rows = [
        ("What is the capital of Portugal?", "Lisbon", "Porto", "Madrid", "Rome", "Lisbon is Portugal's capital."),
        ("What is the capital of Norway?", "Oslo", "Bergen", "Stockholm", "Helsinki", "Oslo is Norway's capital."),
        ("What is the capital of Sweden?", "Stockholm", "Gothenburg", "Oslo", "Copenhagen", "Stockholm is Sweden's capital."),
        ("What is the capital of Finland?", "Helsinki", "Turku", "Tallinn", "Stockholm", "Helsinki is Finland's capital."),
        ("What is the capital of Denmark?", "Copenhagen", "Aarhus", "Oslo", "Berlin", "Copenhagen is Denmark's capital."),
        ("What is the capital of Ireland?", "Dublin", "Cork", "Belfast", "Cardiff", "Dublin is the capital of Ireland."),
        ("What is the capital of Austria?", "Vienna", "Salzburg", "Bern", "Prague", "Vienna is Austria's capital."),
        ("What is the capital of Hungary?", "Budapest", "Bucharest", "Bratislava", "Belgrade", "Budapest is Hungary's capital."),
        ("What is the capital of Romania?", "Bucharest", "Budapest", "Sofia", "Chisinau", "Bucharest is Romania's capital."),
        ("What is the capital of Bulgaria?", "Sofia", "Varna", "Skopje", "Athens", "Sofia is Bulgaria's capital."),
        ("What is the capital of Greece?", "Athens", "Thessaloniki", "Nicosia", "Rome", "Athens is Greece's capital."),
        ("What is the capital of Poland?", "Warsaw", "Krakow", "Prague", "Vilnius", "Warsaw is Poland's capital."),
        ("What is the capital of the Czech Republic?", "Prague", "Brno", "Vienna", "Warsaw", "Prague is the Czech Republic's capital."),
        ("What is the capital of Slovakia?", "Bratislava", "Prague", "Ljubljana", "Zagreb", "Bratislava is Slovakia's capital."),
        ("What is the capital of Slovenia?", "Ljubljana", "Bratislava", "Zagreb", "Sarajevo", "Ljubljana is Slovenia's capital."),
        ("What is the capital of Croatia?", "Zagreb", "Split", "Ljubljana", "Belgrade", "Zagreb is Croatia's capital."),
        ("What is the capital of Serbia?", "Belgrade", "Novi Sad", "Sarajevo", "Sofia", "Belgrade is Serbia's capital."),
        ("What is the capital of Albania?", "Tirana", "Durres", "Skopje", "Podgorica", "Tirana is Albania's capital."),
        ("What is the capital of Estonia?", "Tallinn", "Riga", "Vilnius", "Helsinki", "Tallinn is Estonia's capital."),
        ("What is the capital of Iceland?", "Reykjavik", "Akureyri", "Oslo", "Nuuk", "Reykjavik is Iceland's capital."),
        ("What is the capital of Morocco?", "Rabat", "Casablanca", "Marrakesh", "Algiers", "Rabat is Morocco's capital."),
        ("What is the capital of Algeria?", "Algiers", "Oran", "Tunis", "Rabat", "Algiers is Algeria's capital."),
        ("What is the capital of Tunisia?", "Tunis", "Sfax", "Tripoli", "Algiers", "Tunis is Tunisia's capital."),
        ("What is the capital of Kenya?", "Nairobi", "Mombasa", "Kampala", "Dodoma", "Nairobi is Kenya's capital."),
        ("What is the capital of Ethiopia?", "Addis Ababa", "Dire Dawa", "Asmara", "Nairobi", "Addis Ababa is Ethiopia's capital."),
        ("What is the capital of Ghana?", "Accra", "Kumasi", "Lome", "Abuja", "Accra is Ghana's capital."),
        ("What is the capital of Senegal?", "Dakar", "Saint-Louis", "Bamako", "Conakry", "Dakar is Senegal's capital."),
        ("What is the capital of Peru?", "Lima", "Cusco", "Quito", "La Paz", "Lima is Peru's capital."),
        ("What is the capital of Chile?", "Santiago", "Valparaiso", "Lima", "Buenos Aires", "Santiago is Chile's capital."),
        ("What is the capital of Colombia?", "Bogota", "Medellin", "Quito", "Caracas", "Bogota is Colombia's capital."),
        ("What is the capital of Ecuador?", "Quito", "Guayaquil", "Lima", "Bogota", "Quito is Ecuador's capital."),
        ("What is the capital of Uruguay?", "Montevideo", "Salto", "Buenos Aires", "Asuncion", "Montevideo is Uruguay's capital."),
        ("What is the capital of Paraguay?", "Asuncion", "Ciudad del Este", "Montevideo", "La Paz", "Asuncion is Paraguay's capital."),
        ("What is the capital of Cuba?", "Havana", "Santiago de Cuba", "Kingston", "Nassau", "Havana is Cuba's capital."),
        ("What is the capital of Jamaica?", "Kingston", "Montego Bay", "Havana", "Bridgetown", "Kingston is Jamaica's capital."),
        ("What is the capital of New Zealand?", "Wellington", "Auckland", "Canberra", "Christchurch", "Wellington is New Zealand's capital."),
        ("What is the capital of Thailand?", "Bangkok", "Chiang Mai", "Phnom Penh", "Hanoi", "Bangkok is Thailand's capital."),
        ("What is the capital of Vietnam?", "Hanoi", "Ho Chi Minh City", "Bangkok", "Vientiane", "Hanoi is Vietnam's capital."),
        ("What is the capital of Cambodia?", "Phnom Penh", "Siem Reap", "Hanoi", "Bangkok", "Phnom Penh is Cambodia's capital."),
        ("What is the capital of Laos?", "Vientiane", "Luang Prabang", "Hanoi", "Yangon", "Vientiane is Laos's capital."),
        ("What is the capital of Mongolia?", "Ulaanbaatar", "Erdenet", "Astana", "Beijing", "Ulaanbaatar is Mongolia's capital."),
        ("What is the capital of Nepal?", "Kathmandu", "Pokhara", "Thimphu", "Dhaka", "Kathmandu is Nepal's capital."),
        ("What is the capital of Bhutan?", "Thimphu", "Kathmandu", "Paro", "Dhaka", "Thimphu is Bhutan's capital."),
        ("What is the capital of Bangladesh?", "Dhaka", "Chittagong", "Kathmandu", "Islamabad", "Dhaka is Bangladesh's capital."),
        ("Which major desert stretches across much of northern Africa?", "Sahara Desert", "Gobi Desert", "Atacama Desert", "Great Victoria Desert", "The Sahara spans a broad belt of northern Africa."),
        ("On which continent is the Amazon Basin?", "South America", "Africa", "Asia", "North America", "The Amazon Basin occupies a large part of South America."),
        ("On which continent are the Alps?", "Europe", "Asia", "Africa", "South America", "The Alps extend across central Europe."),
        ("On which continent are the Himalayas?", "Asia", "Europe", "Africa", "South America", "The Himalayas lie in Asia."),
        ("Which ocean lies east of Africa?", "Indian Ocean", "Atlantic Ocean", "Arctic Ocean", "Southern Ocean only", "The Indian Ocean borders eastern Africa."),
        ("Which ocean lies west of North America?", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean only", "The Pacific borders the western coast of North America."),
        ("Which ocean lies between the Americas and Europe and Africa?", "Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Southern Ocean", "The Atlantic separates the Americas from Europe and Africa."),
        ("Southern Europe and northern Africa face each other across which body of water?", "Mediterranean Sea", "Baltic Sea", "Arabian Sea", "Coral Sea", "The Mediterranean lies between Europe and Africa."),
        ("Which sea separates the Arabian Peninsula from northeast Africa?", "Red Sea", "Black Sea", "Caspian Sea", "North Sea", "The Red Sea lies between Arabia and northeast Africa."),
        ("Which mountain range runs along western South America?", "Andes", "Rockies", "Alps", "Urals", "The Andes extend along South America's western margin."),
        ("Which mountain range runs through western North America?", "Rocky Mountains", "Andes", "Atlas Mountains", "Carpathians", "The Rocky Mountains form a major western North American range."),
        ("Which mountain range is commonly used as part of the Europe-Asia boundary?", "Ural Mountains", "Pyrenees", "Appalachians", "Drakensberg", "The Urals are a conventional segment of the Europe-Asia divide."),
        ("Which river flows through London?", "Thames", "Seine", "Rhine", "Tiber", "London stands on the River Thames."),
        ("Which river flows through Paris?", "Seine", "Thames", "Danube", "Po", "Paris stands on the River Seine."),
        ("Which river flows through Rome?", "Tiber", "Seine", "Tagus", "Vistula", "Rome is situated on the Tiber."),
        ("Which river flows through Budapest?", "Danube", "Rhine", "Volga", "Elbe", "The Danube flows through Budapest."),
        ("Which river flows through Baghdad?", "Tigris", "Euphrates only", "Jordan", "Indus", "Baghdad lies on the Tigris."),
        ("Which river flows through Bangkok?", "Chao Phraya", "Mekong", "Ganges", "Irrawaddy", "Bangkok is located along the Chao Phraya."),
        ("Which desert covers much of Mongolia and northern China?", "Gobi Desert", "Sahara Desert", "Atacama Desert", "Kalahari Desert", "The Gobi spans parts of Mongolia and northern China."),
        ("Which desert lies along the Pacific coast of Chile and Peru?", "Atacama Desert", "Gobi Desert", "Namib Desert", "Arabian Desert", "The Atacama occupies the Pacific side of northern Chile and southern Peru."),
        ("Which desert lies along the Atlantic coast of Namibia?", "Namib Desert", "Kalahari Desert", "Atacama Desert", "Sahara Desert", "The Namib is a coastal desert in southwestern Africa."),
        ("Which island country lies southeast of India?", "Sri Lanka", "Madagascar", "Iceland", "Cuba", "Sri Lanka is an island immediately southeast of India."),
        ("Which large island lies east of mainland Africa?", "Madagascar", "Greenland", "Borneo", "New Guinea", "Madagascar lies in the Indian Ocean east of southern Africa."),
        ("Which country occupies most of the Iberian Peninsula?", "Spain", "Italy", "Greece", "France", "Spain covers most of the Iberian Peninsula."),
        ("Which country occupies the boot-shaped peninsula in southern Europe?", "Italy", "Portugal", "Greece", "Croatia", "The Italian Peninsula has a characteristic boot shape."),
        ("Which country is shaped around the Jutland Peninsula and nearby islands?", "Denmark", "Norway", "Finland", "Iceland", "Denmark includes Jutland and an archipelago to its east."),
        ("Which line of longitude is defined as 0 degrees?", "Prime Meridian", "International Date Line", "Equator", "Tropic of Cancer", "The Prime Meridian is longitude 0 degrees."),
        ("Which line of latitude is 0 degrees?", "Equator", "Prime Meridian", "Arctic Circle", "Tropic of Capricorn", "The Equator is latitude 0 degrees."),
        ("Which hemisphere is north of the Equator?", "Northern Hemisphere", "Southern Hemisphere", "Eastern Hemisphere only", "Western Hemisphere only", "The Equator divides north from south."),
        ("Which hemisphere is west of the Prime Meridian in the conventional system?", "Western Hemisphere", "Eastern Hemisphere", "Northern Hemisphere", "Southern Hemisphere", "Longitudes west of 0 degrees lie in the Western Hemisphere."),
        ("What is latitude?", "Angular distance north or south of the Equator", "Angular distance east or west of Greenwich", "Elevation above sea level", "Distance from a coastline", "Latitude measures north-south angular position."),
        ("What is longitude?", "Angular distance east or west of the Prime Meridian", "Angular distance north or south of the Equator", "Height above sea level", "Distance to the nearest pole only", "Longitude measures east-west angular position."),
        ("What is a delta?", "Sediment-built land at a river mouth", "A mountain summit", "A desert basin only", "A deep ocean trench", "River deposition can build a delta where flow enters standing water."),
        ("Which description defines a peninsula?", "Land almost surrounded by water", "Water almost surrounded by land", "A narrow ocean current", "A mountain pass", "A peninsula projects from a larger landmass and is bordered by water on most sides."),
        ("Which landform is a narrow strip joining two larger land areas?", "Isthmus", "Strait", "Archipelago", "Delta", "An isthmus joins two larger landmasses."),
        ("What is a strait?", "A narrow water passage connecting larger bodies of water", "A broad desert plateau", "A mountain valley", "A line of latitude", "A strait is a navigable or natural narrow waterway."),
        ("Which term means a group or chain of islands?", "Archipelago", "Inland lake", "Mountain range", "Drainage divide", "An archipelago is a collection of islands."),
        ("What is a watershed?", "Land draining to a common outlet", "A building that stores water only", "A coastal cliff", "An ocean current", "A watershed is the drainage area contributing to one outlet."),
        ("What is a plateau?", "Elevated land with a relatively level surface", "A deep narrow valley", "A coastal waterway", "A sand dune only", "A plateau is a high, broad, relatively flat landform."),
        ("What is a valley?", "Low land between higher areas", "A mountain summit", "A coral island", "A line of longitude", "Valleys are elongated low areas often shaped by rivers or glaciers."),
        ("What is a glacier?", "A persistent mass of moving land ice", "A seasonal rain cloud", "An ocean trench", "A desert wind", "Glaciers are bodies of ice that deform and flow under gravity."),
        ("Which biome is dominated by grasses with few trees because rainfall is moderate or seasonal?", "Grassland", "Tropical rainforest", "Tundra", "Permanent ice", "Grasslands occur where moisture supports grasses but often limits dense forest."),
        ("Which biome is dominated by coniferous forest and has long cold winters?", "Boreal forest", "Savanna", "Tropical rainforest", "Hot desert", "The boreal forest, or taiga, is a cold conifer-dominated biome."),
        ("Which biome receives very little precipitation?", "Desert", "Rainforest", "Wetland", "Temperate rainforest", "Low precipitation defines desert climates."),
    ]

    return [item(*row) for row in rows]


def build_medium_items() -> list[Item]:
    items = [
        item("A location at 25 degrees north and 80 degrees west lies in which hemispheres?", "Northern and Western", "Southern and Eastern", "Northern and Eastern", "Southern and Western", "Positive north latitude and west longitude place it north of the Equator and west of Greenwich."),
        item("A location at 30 degrees south and 150 degrees east lies in which hemispheres?", "Southern and Eastern", "Northern and Western", "Southern and Western", "Northern and Eastern", "South latitude and east longitude identify the Southern and Eastern Hemispheres."),
        item("If you travel due east along the Equator, which coordinate changes most directly?", "Longitude", "Latitude", "Elevation necessarily", "Hemisphere north-south position", "East-west travel changes longitude while Equatorial latitude remains zero."),
        item("If you travel due north along one meridian, which coordinate changes?", "Latitude", "Longitude", "Time zone necessarily every kilometer", "Elevation only", "North-south movement along a meridian changes latitude."),
        item("Why are lines of longitude closest together near the poles?", "All meridians converge at the poles", "Earth becomes flat at the poles", "Latitude lines merge there", "Oceans pull them together", "Meridians are great-circle halves meeting at both poles."),
        item("Why do time zones generally change with longitude?", "Earth rotates, bringing different longitudes into sunlight at different times", "Latitude controls Earth's rotation", "Mountains stop clocks", "Ocean currents set legal time", "Earth rotates 360 degrees in about 24 hours, linking solar time to longitude."),
        item("A city is three time zones east of another. When it is noon in the western city, what is the local time in the eastern city under standard offsets?", "3 p.m.", "9 a.m.", "Noon", "Midnight", "Moving east advances standard time, so three zones add three hours."),
        item("A city is five time zones west of a location where it is 18:00. What is the city's local time under standard offsets?", "13:00", "23:00", "18:05", "05:00", "Moving five zones west subtracts five hours: 18:00 - 5 = 13:00."),
        item("Why does crossing the International Date Line westward normally advance the calendar date?", "It compensates for accumulated time-zone changes around Earth", "Earth stops rotating there", "Latitude becomes zero", "The Sun rises twice instantly", "The date adjustment maintains a consistent global calendar after circling longitudes."),
        item("At the June solstice, which hemisphere is tilted toward the Sun?", "Northern Hemisphere", "Southern Hemisphere", "Eastern Hemisphere", "Western Hemisphere", "Earth's north axial end tilts toward the Sun at the June solstice."),
        item("At the December solstice, which hemisphere has its summer?", "Southern Hemisphere", "Northern Hemisphere", "Both have summer", "Neither hemisphere", "The Southern Hemisphere tilts toward the Sun around the December solstice."),
        item("Why are annual temperature changes usually smaller near the Equator?", "Solar angle and day length vary less through the year", "The Equator receives no sunlight", "Earth is farther from the Sun there", "Longitude prevents seasons", "Low latitudes maintain relatively high solar angles year-round."),
        item("Why are polar regions generally colder than tropical regions?", "Sunlight arrives at a lower angle and spreads over more surface", "They are always farther from Earth's center", "Oceans contain no heat", "The poles never receive sunlight", "Low solar angles reduce energy received per unit area."),
        item("Why can a high mountain be cold even at low latitude?", "Air temperature generally decreases with elevation in the troposphere", "Latitude changes at the summit", "Mountains are farther from Earth's core", "Rock cannot absorb sunlight", "Lower pressure and adiabatic cooling contribute to cooler high elevations."),
        item("Which climate is most likely near 30 degrees latitude on a continent's western side under descending subtropical air?", "Dry desert climate", "Polar ice climate", "Humid equatorial rainforest", "Tundra", "Descending subtropical air suppresses clouds and favors aridity."),
        item("Why are many tropical rainforests near the Equator?", "Strong heating promotes rising moist air and frequent convection", "The Equator is permanently frozen", "Trade winds never carry moisture", "Day length is zero", "Equatorial convergence and heating support abundant rainfall."),
        item("What is a rain shadow?", "A dry area on the leeward side of a mountain range", "A permanent river under a glacier", "A tropical cyclone's eye", "A coastal tide", "Mountains force moisture loss on the windward side, leaving drier descending air leeward."),
        item("Which side of a mountain commonly receives more orographic precipitation?", "Windward side", "Leeward side", "Both always receive identical rain", "The side facing the Equator only", "Moist air rises, cools, and condenses on the windward slope."),
        item("Why do west coasts in midlatitudes often receive maritime influence?", "Prevailing westerlies carry ocean air inland", "Earth rotates eastward only over land", "Rivers reverse wind direction", "Longitude removes moisture", "Midlatitude westerly circulation brings air from oceans onto west coasts."),
        item("What is continentality?", "Large temperature variation associated with distance from ocean moderation", "A measure of mountain height", "The number of continents", "A river's discharge", "Land interiors heat and cool more rapidly than oceans."),
        item("Which current type generally warms an adjacent coast?", "A warm ocean current flowing from lower latitudes", "A cold current from polar waters", "An underground river", "A tidal bore only", "Warm currents transfer heat poleward and moderate nearby coastal air."),
        item("Why can cold ocean currents promote coastal deserts?", "They stabilize cool lower air and reduce convection and rainfall", "They boil seawater", "They increase humidity to 100% rainfall everywhere", "They move mountains", "Cold surfaces suppress rising moist air even when fog occurs."),
        item("Which process primarily erodes a V-shaped valley?", "River downcutting", "Continental glaciation", "Wind deposition", "Coral growth", "Running water cuts narrow V-shaped valleys in uplands."),
        item("Which process primarily carves a U-shaped valley?", "Glacial erosion", "River meandering", "Delta deposition", "Dune migration", "Valley glaciers widen and deepen valleys into a U-shaped cross-section."),
        item("Why does a river commonly meander across a floodplain?", "Outer-bank erosion and inner-bank deposition shift its bends", "The river has no current", "Tides create every bend inland", "Mountains pull water sideways", "Velocity differences across bends drive lateral channel migration."),
        item("Where is a river's discharge usually greatest under normal downstream development?", "Nearer its mouth after tributaries join", "At every source spring only", "At drainage divides", "At the highest waterfall necessarily", "Tributaries generally add water as the drainage network grows downstream."),
        item("Why does a river deposit sediment when it enters a lake?", "Its velocity and transport capacity decrease", "Gravity stops acting", "Water becomes solid instantly", "The river gains infinite energy", "Slower flow cannot carry the same sediment load."),
        item("What forms an alluvial fan?", "Sediment deposition where a steep stream reaches flatter land", "Glacial ice at a pole", "Coral growth in deep ocean", "Wind erosion of a cliff", "A sharp drop in stream gradient causes sediment to spread outward."),
        item("Why are floodplains often fertile?", "Repeated floods deposit fine mineral-rich sediment", "They receive no water", "Bedrock is always volcanic", "Salt permanently sterilizes them", "Overbank deposition renews alluvial soils."),
        item("What is river capture?", "One stream diverts the headwaters of another through erosion", "A dam stores water", "A delta becomes an island", "A glacier freezes a river", "Headward erosion can breach a divide and redirect drainage."),
        item("What distinguishes a tributary from a distributary?", "A tributary joins a larger stream; a distributary branches away", "Both terms mean the river source", "A tributary flows only underground", "A distributary always joins upstream", "Tributaries add flow, while distributaries divide it."),
        item("Why do deltas not form at every river mouth?", "Strong waves, tides, or deep water may remove sediment faster than it accumulates", "Rivers carry no sediment", "All coasts are identical", "Fresh water cannot enter oceans", "Delta growth requires deposition to exceed marine removal."),
        item("Which tectonic setting builds a mid-ocean ridge?", "Divergent oceanic plate boundary", "Continental collision only", "Transform fault only", "Stable craton", "Seafloor spreading creates new oceanic crust at divergent ridges."),
        item("Which tectonic setting commonly builds a fold mountain belt such as the Himalayas?", "Continental collision", "Mid-ocean divergence", "Hotspot under oceanic crust only", "Passive margin", "Collision compresses and thickens continental crust."),
        item("Why do many earthquakes occur around the Pacific Rim?", "Numerous active plate boundaries surround the Pacific", "The Pacific contains no crust", "Latitude 0 crosses it", "Ocean water causes all earthquakes", "Subduction and transform boundaries concentrate tectonic stress."),
        item("What is a volcanic hotspot?", "Localized mantle upwelling that can create volcanoes away from plate boundaries", "Any cold ocean current", "A city near a volcano", "A plate boundary trench only", "Hotspots can form age-progressive volcanic chains as plates move overhead."),
        item("How can an island chain record plate motion over a hotspot?", "Island ages increase away from the currently active volcano", "All islands form simultaneously", "Older islands move toward the core", "Latitude becomes constant", "A moving plate carries extinct volcanoes away while a new one forms over the hotspot."),
        item("What is a passive continental margin?", "A continent-ocean transition not located at an active plate boundary", "A subduction trench", "A transform fault through a continent", "A volcanic island arc", "Passive margins are tectonically quiet edges within a plate."),
        item("Why is oceanic crust generally younger than continental crust?", "It is continually created at ridges and recycled at subduction zones", "Oceans formed after every continent yesterday", "Ocean water dissolves all old rock instantly", "Continental crust is never altered", "Plate tectonics renews ocean basins on geologic timescales."),
        item("Which soil horizon commonly contains the most decomposed organic material?", "Topsoil near the surface", "Unweathered bedrock", "Parent rock only", "Deep groundwater", "Surface horizons receive litter and humus."),
        item("Why can deforestation increase soil erosion?", "Roots no longer bind soil and canopy no longer reduces rainfall impact", "Trees create all erosion", "Bare soil absorbs every raindrop", "Rivers stop flowing", "Vegetation protects and stabilizes soil."),
        item("What is desertification?", "Degradation of dryland productivity", "Natural formation of every desert", "Growth of tropical forest", "Creation of glaciers", "Vegetation loss and soil degradation can reduce dryland productivity."),
        item("What is urbanization?", "Increase in the share or number of people living in urban settlements", "Movement only from cities to farms", "Mountain formation", "River erosion", "Urbanization describes population concentration in towns and cities."),
        item("What is population density?", "Number of people per unit area", "Total births per year only", "Average elevation", "Distance between capitals", "Density relates population count to land area."),
        item("Why are major settlements often located at river crossings?", "Crossings concentrate transport routes and access to water", "Rivers prevent trade", "Flooding is impossible there", "Latitude requires cities", "Accessible crossing points become transport nodes."),
        item("Why do natural harbors favor city growth?", "They provide sheltered water for ships and trade", "They eliminate land transport", "They create mountains", "They prevent fishing", "Sheltered anchorages support maritime exchange."),
        item("What term describes a continuous urban area created when neighboring settlements grow together?", "Conurbation", "Isolated hamlet", "River delta", "Mountain pass", "Urban expansion can merge once-separate towns into a conurbation."),
        item("What is a site factor for a settlement?", "A characteristic of the location itself, such as relief or water", "A connection to other places only", "A national flag", "A time zone", "Site describes local physical conditions; situation describes relative location."),
        item("What is a situation factor for a settlement?", "Its position relative to routes, markets, and other places", "Its soil directly under one building only", "Its latitude alone", "Its building material", "Situation concerns a place's connections and regional context."),
        item("Why are population pyramids useful?", "They show age and sex structure", "They map mountain elevation", "They show only total land area", "They measure rainfall", "Population pyramids display cohorts by age and sex."),
        item("A population pyramid has a broad base and narrow top. What pattern does this usually suggest?", "High birth rates and a young population", "No children", "An entirely elderly population", "Zero population change necessarily", "A broad base represents large younger cohorts."),
        item("What is migration?", "Movement of people with a change of usual residence", "Daily weather change", "River sediment transport only", "Plate movement", "Migration changes where people live."),
        item("What is a push factor in migration?", "A condition encouraging people to leave an origin", "An attraction at a destination", "A line of longitude", "A river tributary", "Push factors make the current location less desirable."),
        item("What is a pull factor in migration?", "A condition attracting people to a destination", "A reason to leave an origin only", "A tectonic force", "A climate graph", "Pull factors make a destination appealing."),
        item("What is a renewable resource?", "A resource replenished on a human timescale if managed appropriately", "A resource that can never be depleted", "Only fossil fuel", "Any imported product", "Renewable flows or stocks can recover relative to human use."),
        item("Why is groundwater overuse a concern?", "Withdrawal can exceed recharge and lower the water table", "Aquifers refill instantly", "Groundwater has no connection to wells", "Pumping creates rainfall", "Persistent overdraft depletes stored groundwater."),
        item("What is salinization of irrigated soil?", "Accumulation of salts as water evaporates", "Removal of every mineral", "Formation of glaciers", "Increase in forest cover", "Irrigation water leaves dissolved salts behind when it evaporates."),
        item("Why can terracing reduce erosion on steep farmland?", "It shortens slopes and slows runoff", "It makes slopes steeper", "It removes all soil", "It increases river velocity", "Level steps reduce downhill water speed and soil loss."),
        item("What is a biome?", "A broad ecological region defined by climate and dominant vegetation", "A single city district", "A tectonic plate", "A river channel", "Climate supports characteristic vegetation and associated communities."),
        item("Why are savannas dominated by grass with scattered trees?", "Seasonal rainfall, fire, and grazing limit continuous forest", "They receive no sunlight", "Permafrost prevents all roots", "Rain falls every day equally", "Seasonal moisture and disturbance maintain open tropical grassland."),
        item("What distinguishes weather from climate?", "Weather is short-term atmospheric state; climate is long-term pattern", "Weather covers centuries only", "Climate changes hourly", "They are identical", "Climate summarizes typical weather and variability over long periods."),
        item("What is a monsoon?", "A seasonal reversal or strong shift in prevailing winds and rainfall", "A daily sea breeze only", "A permanent polar wind", "A volcanic eruption", "Land-sea heating contrasts drive major seasonal circulation changes."),
        item("Why are tropical cyclones powered by warm ocean water?", "Condensation of evaporated water releases latent heat", "Cold water creates stronger evaporation", "Ocean salt becomes fuel", "Earthquakes spin the storm", "Warm seas supply moisture and heat to organized convection."),
        item("Why do tropical cyclones weaken over land?", "They lose their warm-ocean moisture source and encounter greater friction", "Land adds unlimited heat", "Mountains increase ocean evaporation", "Air stops rotating", "Removal from warm water cuts energy supply."),
        item("What is the eye of a mature tropical cyclone?", "A relatively calm central region surrounded by the eyewall", "The outermost rainband", "A cold front", "The storm's path", "Subsiding air produces relative calm in the center."),
        item("What is a sea breeze?", "Daytime wind from sea toward warmer land", "Nighttime wind from land to sea", "A global trade wind", "A mountain downslope wind", "Land heats faster by day, drawing cooler marine air inland."),
        item("What is a land breeze?", "Nighttime wind from cooler land toward relatively warmer water", "Daytime wind from sea to land", "A monsoon lasting months", "A polar jet", "Land cools faster at night, reversing the local pressure gradient."),
        item("Why does air pressure generally decrease with elevation?", "Less overlying air remains above", "Gravity increases upward", "Air becomes liquid", "Latitude changes", "Atmospheric pressure reflects the weight of air overhead."),
        item("What is relative humidity?", "Actual water vapor relative to saturation at the same temperature", "Total rainfall in a year", "Air pressure divided by wind speed", "Cloud height", "Relative humidity compares vapor content with temperature-dependent capacity."),
        item("Why can relative humidity rise overnight without adding water vapor?", "Cooling lowers the air's saturation vapor capacity", "Night creates new oceans", "Air loses all pressure", "Wind stops permanently", "The same vapor amount is a larger fraction of saturation at lower temperature."),
        item("What does a contour line connect on a topographic map?", "Points of equal elevation", "Points of equal longitude only", "Cities of equal population", "Areas with equal rainfall necessarily", "Contour lines represent a constant elevation."),
        item("What do closely spaced contour lines indicate?", "A steep slope", "A flat plain", "Sea level only", "A wide river", "Elevation changes rapidly over a short horizontal distance."),
        item("What do widely spaced contour lines indicate?", "A gentle slope", "A vertical cliff", "A deep trench necessarily", "A city center", "Elevation changes slowly over horizontal distance."),
        item("How do contour lines usually form a V when crossing a stream valley?", "The V points upstream", "The V points downstream in every case", "They become straight latitude lines", "They stop at water", "Contours bend toward higher elevation upstream."),
        item("What does map scale express?", "Relationship between map distance and ground distance", "Direction of north only", "Elevation above sea level", "Population density", "Scale converts measured map length to real-world distance."),
        item("On a map where 2 centimeters represent 10 kilometers, what does 7 centimeters represent?", "35 kilometers", "70 kilometers", "14 kilometers", "5 kilometers", "Each centimeter represents 5 kilometers, so 7 represents 35."),
        item("A map scale is 1:50,000. What ground distance does 2 centimeters represent?", "1 kilometer", "100 kilometers", "500 meters", "10 kilometers", "Two map centimeters equal 100,000 ground centimeters, or 1 kilometer."),
        item("Which map projection property is most important for ocean navigation bearings?", "Preservation of local angles", "Perfect preservation of all areas", "No distortion anywhere", "Equal population symbols", "Conformal projections preserve local angles and compass directions."),
        item("Why must every flat world map distort some property?", "A curved surface cannot be flattened without distortion", "Paper has no coordinates", "Earth has no measurable size", "Longitude is imaginary", "Map projection transforms a sphere-like surface onto a plane."),
        item("What does a choropleth map show?", "Rates or values shaded by area", "Individual heights with contour lines only", "Only road directions", "Ocean depth profiles", "Choropleth shading encodes an attribute for predefined regions."),
        item("Why should raw population counts be used cautiously on choropleth maps?", "Large regions may appear dominant even when density or rate is low", "Counts cannot be numbers", "Regions have no boundaries", "Color cannot represent values", "Rates or densities often support fairer comparison among differently sized units."),
        item("What does a dot-density map use?", "Dots representing a specified quantity distributed across an area", "Contour lines for elevation", "Arrows for wind only", "One symbol per country regardless of value", "Each dot stands for a set amount of the mapped phenomenon."),
        item("What is a geographic information system?", "A system for storing, analyzing, and visualizing spatial data", "Only a paper atlas", "A weather instrument", "A type of longitude", "GIS links data to locations and supports spatial analysis."),
        item("What does remote sensing collect?", "Information about Earth without direct contact, often from aircraft or satellites", "Only interviews", "Underground samples only", "Time-zone rules", "Sensors measure reflected or emitted energy from a distance."),
        item("Why are false-color satellite images useful?", "They display nonvisible wavelengths in visible colors", "They reproduce only natural eye colors", "They remove all spectral information", "They show political borders automatically", "Assigned colors can highlight vegetation, moisture, or temperature signatures."),
        item("What does GPS determine using signals from multiple satellites?", "Position and time", "Only rainfall", "Population density", "Rock type directly", "Receiver timing of satellite signals supports trilateration."),
        item("Why are at least four satellite signals commonly used for a 3D GPS fix?", "They solve three position coordinates plus receiver clock error", "Each satellite gives one continent", "Four are needed to identify north", "Signals cannot travel through air", "The unknown receiver clock offset adds a fourth variable."),
        item("Which region is downstream from a dam most directly affected by reduced sediment supply?", "River channel, delta, and coast below the dam", "The river's source only", "A different continent", "The upper atmosphere", "Reservoirs trap sediment that would otherwise move downstream."),
        item("Why can removal of mangroves increase coastal vulnerability?", "Mangroves reduce wave energy and stabilize sediment", "Mangroves create all storms", "Roots deepen ocean trenches", "They stop tides globally", "Vegetation buffers waves and binds coastal soils."),
        item("What is coastal longshore drift?", "Sediment transport along shore by angled waves and return flow", "Deep-ocean circulation", "River flow toward a source", "Movement of tectonic plates", "Oblique wave approach produces net along-coast sediment motion."),
        item("Why may a groyne widen one beach but narrow a beach farther down-current?", "It traps sediment moving by longshore drift", "It creates new sand from water", "It reverses Earth's rotation", "It stops every wave", "Interrupting sediment transport causes updrift accumulation and downdrift shortage."),
        item("What forms a fjord?", "A glacial valley flooded by the sea", "A river delta in a desert", "A coral atoll", "A volcanic crater lake only", "Sea-level flooding of a deep U-shaped glacial valley creates a fjord."),
        item("What forms an atoll?", "Coral growth around a subsiding volcanic island", "River deposition at a mouth", "Glacial erosion", "Wind erosion of a mesa", "A reef can persist near sea level as the central island subsides."),
        item("Why are coral reefs concentrated in shallow clear tropical water?", "Symbiotic algae require light and warm conditions", "Coral grows only under ice", "Deep muddy water provides more light", "Freshwater is required", "Light-dependent symbionts and temperature constrain reef-building coral."),
        item("What is an exclusive economic zone conceptually associated with?", "Coastal-state rights over marine resources in an offshore zone", "Ownership of all oceans", "A line of latitude", "A mountain boundary", "An EEZ grants specified resource rights offshore under maritime law."),
        item("What is landlocked country?", "A country without a coastline on the open ocean", "An island country", "A country entirely below sea level", "A country with no rivers", "Landlocked states lack direct ocean coastline."),
        item("Why can landlocked countries face higher trade transport costs?", "Goods often cross neighboring territory to reach seaports", "They cannot use roads", "All borders are closed", "Distance has no effect", "Additional overland distance and border procedures can raise costs."),
        item("What is a transshipment hub?", "A node where cargo transfers between routes or vehicles", "A farm producing one crop", "A river source", "A climate boundary", "Hubs consolidate and redistribute flows through transport networks."),
        item("What is a hinterland?", "The inland area served by a port or city", "The central business district only", "An ocean trench", "A mountain summit", "A port's hinterland supplies and receives its cargo flows."),
        item("Why do many railways follow river valleys through mountains?", "Valleys offer gentler gradients and passes", "Rivers always run straight", "Trains require water beneath tracks", "Mountains have no valleys", "Transport routes minimize steep climbs and construction difficulty."),
        item("What is a nodal region?", "An area organized around a central focal point", "An area with one uniform climate only", "A tectonic plate", "A latitude band", "Flows and connections link a nodal region to its center."),
        item("What is a formal region?", "An area defined by a shared measurable characteristic", "An area defined only by personal perception", "A single road junction", "Any watershed necessarily", "Formal regions use criteria such as language, climate, or administration."),
        item("What is a perceptual region?", "An area people recognize through shared ideas or identity", "A region with exact legal boundaries only", "A drainage basin", "A time zone", "Perceptual regions reflect cultural understanding rather than one fixed boundary."),
        item("Why can two geographic regions overlap?", "Regions can be defined by different physical, cultural, or functional criteria", "Every place belongs to exactly one region", "Coordinates prevent overlap", "Maps cannot show layers", "Different regional concepts partition space in different ways."),
        item("What is a drainage divide?", "High ground separating neighboring watersheds", "The deepest point of a river", "A dam across a stream", "A delta channel", "Water on opposite sides of a divide flows toward different drainage outlets."),
        item("Why do braided rivers have multiple shifting channels?", "Abundant sediment and variable flow create unstable bars", "They carry no sediment", "They flow only through bedrock canyons", "Tides fix one channel", "Deposition of coarse load splits flow around bars that migrate."),
        item("What is a demographic transition?", "Long-term shift from high birth and death rates toward low rates", "Daily movement between home and work", "A change of time zone", "River migration", "Industrial and social change often alters mortality and fertility in stages."),
        item("What is commuting?", "Regular travel between residence and work or study", "Permanent migration to another country", "Seasonal river flooding", "Ocean circulation", "Commuting is recurrent travel without changing usual residence."),
        item("Why do central business districts often have high land values?", "Accessibility and competition for central locations are high", "They have no transport", "Land is unlimited there", "Elevation fixes prices", "Concentrated services and route convergence create strong demand for central space."),
        item("What is sustainable yield of a renewable resource?", "Use that does not exceed long-term replenishment", "The largest possible one-time extraction", "Any use that makes profit", "Extraction after the resource is gone", "Sustainable yield keeps withdrawals within regenerative capacity."),
    ]

    if len(items) != 110:
        raise ValueError(
            f"Expected 110 medium geography items, found {len(items)}"
        )

    return items


def build_hard_items() -> list[Item]:
    return [
        item("At 15 degrees of longitude per hour, what local solar-time difference corresponds to 45 degrees of longitude?", "3 hours", "45 hours", "1 hour", "6 hours", "Earth rotates 45 degrees in 45/15 = 3 hours."),
        item("A flight crosses the International Date Line eastward on Tuesday without considering travel duration. What calendar adjustment is normally made?", "Move back to Monday", "Move forward to Wednesday", "Keep Tuesday everywhere", "Add one month", "Crossing eastward subtracts one calendar day."),
        item("City A is at UTC+2 and City B at UTC-5. When it is 18:00 in City A, what time is it in City B?", "11:00", "01:00 next day", "13:00", "23:00", "City B is seven hours behind City A, so 18:00 becomes 11:00."),
        item("A place at 60 degrees north experiences very long June days. Which combination explains this?", "High latitude and Northern Hemisphere axial tilt toward the Sun", "Longitude and ocean salinity", "Southern tilt toward the Sun", "Proximity to the Equator", "At the June solstice, northern high latitudes remain illuminated for long arcs."),
        item("Moist air rises 2 kilometers over a mountain, cools, rains, then descends. Why is the descending air often warmer and drier at equal elevation?", "It lost moisture and warms by compression on descent", "It gains water from rock", "Gravity stops acting", "Latitude changes across the ridge", "Rainout and adiabatic warming produce the foehn or chinook effect."),
        item("A river's gradient decreases sharply while discharge remains high. What paired change is most likely?", "Lower velocity and greater deposition", "Higher velocity and no deposition", "No change in sediment transport", "Immediate evaporation", "Reduced slope lowers stream energy and carrying capacity."),
        item("A coastline has cliffs, wave-cut notches, and a broad rock platform. What dominant process is indicated?", "Marine erosion and cliff retreat", "River delta growth", "Glacial deposition", "Coral atoll formation", "Wave attack undercuts cliffs, whose retreat leaves a platform."),
        item("Why can pumping from a coastal aquifer cause saltwater intrusion?", "Lower freshwater pressure allows seawater to move inland", "Pumping turns salt into fresh water", "Ocean level becomes zero", "Aquifers become impermeable", "Fresh groundwater normally holds back denser seawater; drawdown weakens that gradient."),
        item("Two drainage basins receive equal rainfall, but one is urbanized. Why may its flood peak be higher and earlier?", "Impervious surfaces speed runoff and reduce infiltration", "Buildings absorb all rain", "Urban areas have no gravity", "Rivers flow uphill", "Paved surfaces and drains shorten water travel time to channels."),
        item("A population has birth rate 18 per thousand, death rate 7 per thousand, and net migration -3 per thousand. What is its net annual change rate?", "8 per thousand increase", "28 per thousand increase", "14 per thousand decrease", "4 per thousand increase", "Natural increase is 11 per thousand; adding -3 gives 8 per thousand."),
        item("A country has a rising elderly share and a shrinking working-age share. Which challenge is most direct?", "Greater dependency pressure on pensions and care systems", "Automatic increase in school enrollment", "Elimination of healthcare demand", "Guaranteed rapid population growth", "More retirees per worker can strain support systems."),
        item("Why can a primate city pattern create regional inequality?", "Investment and high-level services concentrate disproportionately in one city", "Every town receives equal functions", "Transport costs vanish", "Rural population becomes zero immediately", "Dominance of one city can pull resources and opportunities from other regions."),
        item("A map has representative fraction 1:250,000. A road measures 6 centimeters. What is its ground length?", "15 kilometers", "1.5 kilometers", "150 kilometers", "25 kilometers", "Six centimeters represent 1,500,000 centimeters, or 15 kilometers."),
        item("On a topographic map, contour lines cross a ridge. Which direction does their V shape point?", "Downhill", "Uphill as in a stream valley", "Due north always", "Toward sea level only", "Across ridges, contour bends point toward lower elevation, opposite the valley rule."),
        item("Why can a Mercator world map exaggerate Greenland relative to equatorial Africa?", "Its scale increases strongly toward the poles", "Greenland is actually larger than Africa", "The Equator is compressed by mountains", "Longitude disappears", "Mercator's conformal projection expands high-latitude areas."),
        item("A satellite image records reflected near-infrared strongly from one field. What surface is a likely explanation?", "Healthy green vegetation", "Deep clear water", "Bare asphalt only", "Fresh snow necessarily", "Healthy leaves strongly reflect near-infrared radiation."),
        item("A glacier's accumulation exceeds ablation for many years. What is the likely mass-balance response?", "The glacier gains mass and may advance", "It must disappear", "Its ice becomes liquid instantly", "It loses mass despite the stated balance", "Positive mass balance increases stored ice, though flow response can lag."),
        item("Why can sea level rise even without adding meltwater?", "Warming seawater expands", "Ocean water becomes denser when heated", "Tides permanently add water", "Continents shrink each summer", "Thermal expansion increases ocean volume."),
        item("A warm current weakens near a high-latitude coast. What local climate effect is plausible?", "Reduced oceanic warming and cooler coastal conditions", "Guaranteed desertification worldwide", "No possible temperature change", "Stronger tropical sunlight", "Less poleward heat transport can reduce maritime warming."),
        item("A region lies near a subduction trench and volcanic arc. Which pair of hazards is most characteristic?", "Strong earthquakes and explosive eruptions", "Only tornadoes and drought", "No tectonic hazards", "Glacial surges and sandstorms only", "Subduction produces megathrust earthquakes and volatile-rich magma."),
        item("A city is built on unconsolidated water-saturated sediment. Why may earthquake shaking be especially damaging?", "Soft sediment can amplify shaking and may liquefy", "Sediment blocks every seismic wave", "Water removes gravity", "Buildings become weightless", "Loose saturated grains can lose strength while basin sediments amplify motion."),
        item("A watershed loses upstream forest and wetlands simultaneously. What combined downstream effect is most plausible?", "Faster runoff, higher flood peaks, and more sediment", "Lower runoff and zero erosion", "Permanent elimination of floods", "No hydrologic change", "Vegetation and wetlands slow, store, and filter water; removing them reverses those effects."),
    ]


def build_geography_items() -> dict[str, list[Item]]:
    easy = build_easy_items()
    medium = build_medium_items()
    hard = build_hard_items()

    if len(easy) != 88:
        raise ValueError(
            f"Expected 88 easy geography items, found {len(easy)}"
        )

    if len(hard) != 22:
        raise ValueError(
            f"Expected 22 hard geography items, found {len(hard)}"
        )

    return {
        "easy": easy,
        "medium": medium,
        "hard": hard,
    }
